"""Render workflow audit events as bot-comment markdown.

This module is pure rendering — no I/O, no GitHub API calls. The publisher
in ``comments_publisher.py`` consumes ``render_row``/``render_comment`` and
calls ``gh``.

Per-workflow design (issue #1, design doc 2026-04-26): each workflow owns
its own ``comments.py``. The code-review workflow's audit-event vocabulary
is what's mapped here; a future testing workflow would have its own.
"""
from __future__ import annotations

from datetime import datetime
from pathlib import Path
from typing import Any, Mapping

MAX_COMMENT_ROWS = 50

# Map audit-action → (emoji, headline). Unknown actions fall back to a generic
# render so we never silently drop a fired event.
_ACTION_RENDERERS: dict[str, tuple[str, str]] = {
    "dispatch-implementation-turn": ("🔄", "Codex coder dispatched"),
    "codex-committed": ("✅", "Codex committed"),
    "internal-review-started": ("🔍", "Internal review started"),
    "internal-review-completed": ("🔍", "Internal review completed"),
    "request-internal-review": ("🔍", "Internal review requested"),
    "publish-ready-pr": ("🚀", "PR published"),
    "push-pr-update": ("📤", "PR updated"),
    "merge-and-promote": ("✅", "Merged + promoted"),
    "operator-attention-transition": ("⚠️", "Operator attention required"),
    "operator-attention-recovered": ("✅", "Recovered — resuming"),
}


def _format_clock(at_iso: str) -> str:
    """ISO-8601 UTC → HH:MM:SS for table display."""
    try:
        # Tolerate trailing 'Z' as well as full ISO with offset.
        cleaned = at_iso.replace("Z", "+00:00") if at_iso.endswith("Z") else at_iso
        return datetime.fromisoformat(cleaned).strftime("%H:%M:%S")
    except (ValueError, TypeError):
        return at_iso  # let it through; better than crashing the publisher


def _detail_for(event: Mapping[str, Any]) -> str:
    action = event.get("action") or ""
    if action == "dispatch-implementation-turn":
        return event.get("model") or event.get("sessionName") or ""
    if action == "codex-committed":
        sha = event.get("commitSha") or event.get("headSha") or ""
        return f"`{sha[:7]}`" if sha else ""
    if action == "internal-review-completed":
        verdict = event.get("verdict") or event.get("review", {}).get("verdict", "")
        findings = event.get("findingsCount") or event.get("findings") or ""
        if findings:
            return f"{verdict} — {findings} findings" if verdict else str(findings)
        return verdict or ""
    if action == "publish-ready-pr":
        pr = event.get("prNumber") or event.get("number")
        return f"#{pr}" if pr else ""
    if action == "push-pr-update":
        sha = event.get("headSha") or ""
        return f"`{sha[:7]}`" if sha else ""
    if action == "merge-and-promote":
        return f"PR #{event.get('mergedPrNumber') or ''}"
    if action == "operator-attention-transition":
        return event.get("reason") or ""
    return event.get("summary") or ""


def render_row(event: Mapping[str, Any]) -> str:
    """Render one audit event as a markdown table row."""
    action = event.get("action") or "unknown"
    emoji, headline = _ACTION_RENDERERS.get(action, ("•", action))
    detail = _detail_for(event)
    clock = _format_clock(event.get("at") or "")
    return f"| {clock} | {emoji} {headline} | {detail} |"


def append_row(existing_rows: list[str], new_row: str) -> list[str]:
    """Insert ``new_row`` at the top, cap the list at MAX_COMMENT_ROWS."""
    out = [new_row, *existing_rows]
    return out[:MAX_COMMENT_ROWS]


def render_comment(
    *,
    issue_number: int,
    workflow_state: str,
    rows: list[str],
    is_operator_attention: bool,
) -> str:
    """Render the full bot-comment markdown body."""
    if is_operator_attention:
        header_state = "⚠️ operator-attention"
    else:
        header_state = workflow_state
    rows = rows[:MAX_COMMENT_ROWS]
    table_header = "| Time (UTC) | Event | Detail |\n|---|---|---|"
    body_rows = "\n".join(rows) if rows else "_(no events yet)_"
    now = datetime.utcnow().strftime("%Y-%m-%d %H:%M:%S UTC")
    return (
        f"🤖 **Daedalus lane status** — lane #{issue_number} · `{header_state}`\n\n"
        f"{table_header}\n{body_rows}\n\n"
        f"_Last update: {now} · auto-generated by Daedalus_"
    )


# ─── Lane-comments state file ────────────────────────────────────────────
# Persisted at <workflow_root>/runtime/state/lane-comments/<issue>.json
# Schema: {comment_id, last_rendered_text, rows, last_action}
#   - comment_id: GitHub comment id (str) or None when no comment created yet
#   - last_rendered_text: full body of the last successful PATCH/POST (str|None)
#   - rows: chronological-newest-first list of rendered table rows (list[str])
#   - last_action: name of the last audit action that fired (for dedupe / debug)

import json as _json
import os as _os


def state_path_for_issue(state_dir: Path, issue_number: int) -> Path:
    return Path(state_dir) / f"{issue_number}.json"


def _empty_state() -> dict[str, Any]:
    return {"comment_id": None, "last_rendered_text": None, "rows": [], "last_action": None}


def load_state(state_dir: Path, issue_number: int) -> dict[str, Any]:
    path = state_path_for_issue(state_dir, issue_number)
    if not path.exists():
        return _empty_state()
    try:
        return _json.loads(path.read_text(encoding="utf-8"))
    except (_json.JSONDecodeError, OSError):
        return _empty_state()


def save_state(state_dir: Path, issue_number: int, state: dict[str, Any]) -> None:
    path = state_path_for_issue(state_dir, issue_number)
    path.parent.mkdir(parents=True, exist_ok=True)
    tmp = path.with_suffix(path.suffix + ".tmp")
    tmp.write_text(_json.dumps(state), encoding="utf-8")
    _os.replace(tmp, path)
